/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.engsoft.view;

import br.com.engsoft.controller.ControllerInteracao;
import java.awt.GraphicsDevice;
import java.awt.Window;
import javax.swing.JPanel;

/**
 *
 * @author MATEUS
 */
public class Moldura extends javax.swing.JFrame {

    /**
     * Creates new form Moldura
     */
    public Moldura() {
        this.setUndecorated(true);
        this.setResizable(false);
        this.setTitle("EngSoft");
        this.setSize(1024, 768);
        JPanel background = new JPanel();
        background.setBackground(new java.awt.Color(0,51,102));
        
        initComponents();
        /**
         * Modo FulScreen da Moldura
         * API: Full-Screen Exclusive Mode
         * Caso dispositivo de display suportar será ativado o modo tela cheia.
         */
        GraphicsDevice myDevice = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();        
        Window myWindow = this;                
        if(myDevice.isFullScreenSupported()) myDevice.setFullScreenWindow(myWindow);         
        else this.setUndecorated(false);
        
        this.jDesktopPane.add(background);                                    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        registroSistema = new javax.swing.JMenuItem();
        solicitacaoSistema = new javax.swing.JMenuItem();
        ordensServico = new javax.swing.JMenuItem();
        fluxoAprovacoesOS = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        consultaAeronave = new javax.swing.JMenuItem();
        consultaCliente = new javax.swing.JMenuItem();
        consultaContratoSLA = new javax.swing.JMenuItem();
        consultaManutencao = new javax.swing.JMenuItem();
        consultaEquipamento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane.setBackground(new java.awt.Color(0, 51, 102));
        jDesktopPane.setLayout(new java.awt.CardLayout());

        jMenuBar1.setDoubleBuffered(true);
        jMenuBar1.setFocusTraversalPolicyProvider(true);

        jMenu1.setText("Principal");

        registroSistema.setText("Cadastros do sistema");
        registroSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroSistemaActionPerformed(evt);
            }
        });
        jMenu1.add(registroSistema);

        solicitacaoSistema.setText("Solicitações do sistema");
        solicitacaoSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitacaoSistemaActionPerformed(evt);
            }
        });
        jMenu1.add(solicitacaoSistema);

        ordensServico.setText("Ordens de serviço");
        ordensServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordensServicoActionPerformed(evt);
            }
        });
        jMenu1.add(ordensServico);

        fluxoAprovacoesOS.setText("Fluxo de aprovações O.S.");
        fluxoAprovacoesOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fluxoAprovacoesOSActionPerformed(evt);
            }
        });
        jMenu1.add(fluxoAprovacoesOS);
        jMenu1.add(jSeparator1);

        menuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        consultaAeronave.setText("Aeronaves");
        consultaAeronave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaAeronaveActionPerformed(evt);
            }
        });
        jMenu2.add(consultaAeronave);

        consultaCliente.setText("Clientes");
        consultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaClienteActionPerformed(evt);
            }
        });
        jMenu2.add(consultaCliente);

        consultaContratoSLA.setText("Contratos SLA");
        consultaContratoSLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaContratoSLAActionPerformed(evt);
            }
        });
        jMenu2.add(consultaContratoSLA);

        consultaManutencao.setText("Manutenções");
        consultaManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaManutencaoActionPerformed(evt);
            }
        });
        jMenu2.add(consultaManutencao);

        consultaEquipamento.setText("Equipamento/Almoxarifado");
        consultaEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEquipamentoActionPerformed(evt);
            }
        });
        jMenu2.add(consultaEquipamento);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        // TODO add your handling code here:
        new ControllerInteracao().sairAplicacao();
    }//GEN-LAST:event_menuSairActionPerformed

    private void solicitacaoSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitacaoSistemaActionPerformed
        // TODO add your handling code here:
        new ControllerInteracao().solicitar(this.jDesktopPane, this.getBounds());        
    }//GEN-LAST:event_solicitacaoSistemaActionPerformed

    private void registroSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroSistemaActionPerformed
        // TODO add your handling code here:        
        new ControllerInteracao().registro(this.jDesktopPane, this.getBounds());        
    }//GEN-LAST:event_registroSistemaActionPerformed

    private void consultaManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaManutencaoActionPerformed
        // TODO add your handling code here:
        new ControllerInteracao().consulta(this.jDesktopPane, this.getBounds(),"Manutencao");
    }//GEN-LAST:event_consultaManutencaoActionPerformed

    private void consultaContratoSLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaContratoSLAActionPerformed
        // TODO add your handling code here:
        new ControllerInteracao().consulta(this.jDesktopPane, this.getBounds(),"ContratoSLA");        
    }//GEN-LAST:event_consultaContratoSLAActionPerformed

    private void consultaAeronaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaAeronaveActionPerformed
        // TODO add your handling code here:
        new ControllerInteracao().consulta(this.jDesktopPane, this.getBounds(),"Aeronave");        
    }//GEN-LAST:event_consultaAeronaveActionPerformed

    private void consultaEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEquipamentoActionPerformed
        // TODO add your handling code here:
        new ControllerInteracao().consulta(this.jDesktopPane, this.getBounds(),"Equipamento");        
    }//GEN-LAST:event_consultaEquipamentoActionPerformed

    private void consultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaClienteActionPerformed
        // TODO add your handling code here:
        new ControllerInteracao().consulta(this.jDesktopPane, this.getBounds(),"Cliente");
    }//GEN-LAST:event_consultaClienteActionPerformed

    private void fluxoAprovacoesOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fluxoAprovacoesOSActionPerformed
        // TODO add your handling code here:
        new ControllerInteracao().consulta(this.jDesktopPane, this.getBounds(),"FluxoAprovacaoOS");
    }//GEN-LAST:event_fluxoAprovacoesOSActionPerformed

    private void ordensServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordensServicoActionPerformed
        // TODO add your handling code here:
        new ControllerInteracao().consulta(this.jDesktopPane, this.getBounds(),"OrdemServico");
    }//GEN-LAST:event_ordensServicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem consultaAeronave;
    private javax.swing.JMenuItem consultaCliente;
    private javax.swing.JMenuItem consultaContratoSLA;
    private javax.swing.JMenuItem consultaEquipamento;
    private javax.swing.JMenuItem consultaManutencao;
    private javax.swing.JMenuItem fluxoAprovacoesOS;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem ordensServico;
    private javax.swing.JMenuItem registroSistema;
    private javax.swing.JMenuItem solicitacaoSistema;
    // End of variables declaration//GEN-END:variables
}
